### ISSUE TITLE
Offset currently implemented as pages

### ISSUE THREAD

**Issue by maxcell** [learn-co-curriculum/js-rails-as-api-design-documentation-exercise-b#3]
The current offset protocol we're following is XXX records from the beginning returned to some limit YYY which is useful! I think we should call them page in the url if we want to use it, this, because here we're saying after the first 5 records return the next five (given offset of 5, to limit 5). 

Another way which might be a slightly more fun way of implementing pagination (and [faster](http://allyouneedisbackend.com/blog/2017/09/24/the-sql-i-love-part-1-scanning-large-table/)) would be value based offset. Using the last id to query for the next information after that. So if I give an offset of 5, it means after id 5 get the next 5 afterwards (6, 7, 8, 9, 10). This would make the starting point more flexible, though wouldn't be as good for going previous unless we sorted the first item from the last query.

**Comment by sgharms** [comment]
@maxwellbenton Can you make the call on this one? I'm not sure what the right next step is.

**Comment by maxcell** [comment]
I think just being clear on the instructions what offset should represent could be helpful since the readings/labs haven't used the pagination language before. Overall the exercise was great for the students!

**Comment by maxwellbenton** [comment]
Hey @maxcell,

I went with updating the offset parameter to page in the URL, since it is a pretty useful thing to explore, so now `http://localhost:3000/coffee?limit=5&page=1` will show the coffees 6-10, `limit=10&page2` will show 21-30, etc...

Should be resolved now. Thank you for submitting!
